# Generated by Django 4.2.4 on 2023-08-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_replacephrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replacephrase',
            old_name='Phrase',
            new_name='phrase',
        ),
    ]
