# Generated by Django 4.2.4 on 2023-08-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_rename_phrase_replacephrase_phrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('post_id', models.IntegerField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_website', to='userpanel.website')),
            ],
        ),
    ]
